### ISSUE TITLE
Size is reported incorrectly depending on the scale factor

### ISSUE THREAD

**Issue by colemickens** [cyclopsian/wdisplays#1]
![screenshot-1565900053](https://user-images.githubusercontent.com/327028/63123771-0d4ce700-bfaa-11e9-9f83-63a6d658f5b6.png)

See screenshot. App reports "1920x1080" when the resolution is higher. 

However, when I set the scale to 1.5 from `wdisplays`, it reports the size correctly:
![screenshot-1565900138](https://user-images.githubusercontent.com/327028/63123863-42593980-bfaa-11e9-8230-c2ef48481312.png)

**Comment by colemickens** [comment]
Well, I guess it's wrong both times, assuming it's meant to show screen native resolution, not effective resolution.

**Comment by colemickens** [comment]
(Which I was assuming giving the button next to those boxes shows that native modes for the given output.)

**Comment by cyclopsian** [comment]
This is a bug. It looks like `zxdg_output_v1.logical_size` is returning the effective resolution instead of the real one. I'll get back to you tonight when I can test with an external monitor.

**Comment by cyclopsian** [comment]
Fixed in dd2568a2b48af254f3d54c3814af890fe3757946
