### ISSUE TITLE
When the window is too small, the apply button is not visible

### ISSUE THREAD

**Issue by WhyNotHugo** [cyclopsian/wdisplays#13]
When the window goes below a certain threshold, the "apply" button is not hidden.

This is very problematic when one misconfigures the display to too low-res, since it's not longer possible to apply new settings.

![2020-03-03T14:48:04,474173879+01:00](https://user-images.githubusercontent.com/730811/75781782-22c70a00-5d5e-11ea-9a8e-c26c2188c094.png)

**Comment by cyclopsian** [comment]
I am going to reduce the minimum width of the canvas so that it will fit in 640x480.

**Comment by WhyNotHugo** [comment]
Thanks!
