### ISSUE TITLE
Apply button not visible in fullscreen mode

### ISSUE THREAD

**Issue by WhyNotHugo** [cyclopsian/wdisplays#14]
When running the app fullscreen (had to do this at low-res, because I had insufficient screen real estate), the "Apply" button is not shown. I just realised that the first time I'd used `wdisplays` I'd also ran it full screen, and that's why I couldn't figure it out the first time :sweat_smile: 

![2020-03-03T14:49:54,011700241+01:00](https://user-images.githubusercontent.com/730811/75781913-586bf300-5d5e-11ea-9573-c27b9ffa45d1.png)

I use a tiling WM (sway), so occasionally when my tiles setup it too complex, I just full-screen a window to make it big quickly. However, fullscreening windows is something very commonly done by non-tiling users, rather than manually resizing the window up.

**Comment by cyclopsian** [comment]
This unfortunately is consistent with some other GTK programs. They need special handling to do the right thing when the app is fullscreen. There is no CSS that can change this either. A workaround could be to move the headerbar in/out of a vbox when a fullscreen event is received.

**Comment by WhyNotHugo** [comment]
Thanks for addressing this! :)
