### ISSUE TITLE
How about a release?

### ISSUE THREAD

**Issue by bhepple** [cyclopsian/wdisplays#15]
Hello,

I would like to propose wdisplays for inclusion in fedora. It would be much easier if there were a release against which to build. Are you willing to do that?

If not, I guess I could clone the repo and make my own release but I'd prefer not to do that!!

Thanks

Bob

**Comment by cyclopsian** [comment]
Hi, sorry for the delay, I am getting around to this. I want to make a decision on the open PRs/issues and then I will be ready to cut a 1.0 release.

**Comment by ericonr** [comment]
Hey @cyclopsian, I'm also waiting for a release date in order to put this in Void Linux :)

Do you want any help with the release process? My setup is okay, because I already have it compiled locally, so if you think it's going to take a while, no problemo c:

**Comment by cyclopsian** [comment]
Would you be able to test PR #8? I would like to merge that before release as it significantly reduces CPU usage. When I tested it last year it was buggy and the screen previews were failing to update but it's looking better on my current setup, maybe due to some changes in wlroots. I would like to get confirmation that it works okay on machines with 3 or more monitors, if possible. Please see that PR for the test steps I'm using. I don't have access to that many monitors right now but I may be able to find a way to test this myself by the end of the week.

**Comment by bhepple** [comment]
I only have the laptop but I'll try and dig out my ancient low res monitor ...

**Comment by bhepple** [comment]
Ack! It seems that wdisplays needs wlroots-0.7 and standard fedora-31 only has 0.6

When I was looking at it 2 weeks ago I must have been running a bleeding edge wlroots on my laptop. I'm going to have to wait until fedora moves to 0.7 before I can submit it. In the meantime I'll try to restore my bleeding edge setup and do some testing.

**Comment by cyclopsian** [comment]
I wouldn't worry about testing that now actually, it's broken in wlroots and will be until some adjustments are made to the protocol

**Comment by bhepple** [comment]
No problems. FWIW ea0bf97 seems to run fine on a single laptop screen under sway-1.4 and wlroots-1.10 on fedora. I didn't get as far as digging out the old external monitor!!

**Comment by ericonr** [comment]
@cyclopsian sorry for the delay, I'm not getting github email notifications for some reason. I currently only have access to a single monitor, I used two monitors in my workplace.

**Comment by cyclopsian** [comment]
Things seem mostly stable so I've put out a 1.0 release as-is.

**Comment by bhepple** [comment]
I'll refresh the fedora package to 1.0 once the 0.9 release has worked its way through the system. Sorry for the delay, but I'm almost there.
