### ISSUE TITLE
Display not recognized

### ISSUE THREAD

**Issue by bhepple** [cyclopsian/wdisplays#28]
Originally booked at: https://bugzilla.redhat.com/show_bug.cgi?id=1887672

Description of problem: Getting "Display Unknown" on Settings > Display.  Unable to change resolution.  Also display is not covering the whole screen in the laptop.

Version-Release number of selected component (if applicable):

How reproducible: Always

Steps to Reproduce:
1. Boot System
2. Go to Settings > Display
3. Will get Unknown Display and cannot change display properties.

Actual results:

Expected results: Be able to change display resolution.  Also display is not covering the whole screen.

Additional info:
Fresh install of Fedora 33 with all updates installed since then.
Issue on all kernel versions.
Currently running 5.8.14-300.fc33.x86_64
Laptop is Toshiba SATELLITE P50t-B-108 PSPNVE-0.
It has a 4k display
Resolution: 3840x2160
DE: GNOME 3.38.1
WM: Mutter
GPU: AMD ATI Radeon HD 8850M / R9 M

Laptop has been running several Fedora versions in past, the last Fedora 32, and did not have issue with the display resolution.
Did a clean install to use the btrfs.

**Comment by ammen99** [comment]
Are you sure this is the correct place to discuss this? It seems your problem is with gnome-control-center, not wdisplays (which doesn't even work on gnome)

**Comment by bhepple** [comment]
Sorry mate - brain fart on my part!!
