### ISSUE TITLE
Rotated displays are not handled correctly in preview

### ISSUE THREAD

**Issue by Emantor** [cyclopsian/wdisplays#3]
Hi, thanks for the nice app. However I noticed that with one of my displays in pivot, the preview is rendered wrong, because it is not rotated and thus overlaps the display next to it.

![screenshot](https://user-images.githubusercontent.com/934284/63333470-cb20fe00-c339-11e9-9253-6c73b3d4e44d.png)

**Comment by cyclopsian** [comment]
Should be fixed in bd8fc3f7d436721ef6d6a518a3b9d65d4abe4390, please test. The rotation will still be wrong until you hit apply, because otherwise the preview would get really stretched.

**Comment by Emantor** [comment]
I can confirm the fix, thanks for the fast response :+1:
